#Spigot sound list: "https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html"
#Spigot particle list: "https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html"
#Notifies Plugin Update
notify-update: true
#Enables chunk claiming
worlds:
  - world
  - world_nether
  - world_the_end
#Economy Settings
economy:
  claim-cost: 1250.0
  claim-refund: 750.0
#Claiming Settings
settings:
  claim:
    sound:
      #default values:
      #type: BLOCK_AMETHYST_BLOCK_BREAK
      #volume: 0.7F
      #pitch 1.0F
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.7F
      pitch: 1.0F
    particle:
      #default values:
      #type: TOTEM
      #count: 500
      #offsetX: 6.0
      #offsetY: 15.0
      #offsetZ: 6.0
      type: TOTEM
      count: 500
      offsetX: 6.0
      offsetY: 15.0
      offsetZ: 6.0
  un-claim:
    sound:
      #default values:
      #type: BLOCK_AMETHYST_BLOCK_BREAK
      #volume: 0.7F
      #pitch 1.0F
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.7F
      pitch: 1.0F
    particle:
      #default values:
      #type: SPELL_INSTANT
      #count: 500
      #offsetX: 6.0
      #offsetY: 15.0
      #offsetZ: 6.0
      type: SPELL_INSTANT
      count: 500
      offsetX: 6.0
      offsetY: 15.0
      offsetZ: 6.0
#These will be ignored from interact/playerDamage
hostiles:
  - AREA_EFFECT_CLOUD
  - ARROW
  - BAT
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - DRAGON_FIREBALL
  - DROPPED_ITEM
  - DROWNED
  - EGG
  - ELDER_GUARDIAN
  - ENDER_CRYSTAL
  - ENDER_DRAGON
  - ENDER_PEARL
  - ENDER_SIGNAL
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - EVOKER_FANGS
  - EXPERIENCE_ORB
  - FALLING_BLOCK
  - FIREBALL
  - FIREWORK
  - GHAST
  - GIANT
  - GUARDIAN
  - HOGLIN
  - HUSK
  - ILLUSIONER
  - LIGHTING
  - LLAMA_SPIT
  - MAGMA_CUBE
  - MARKER
  - PHANTOM
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - PLAYER
  - PRIMED_TNT
  - RAVAGER
  - SHULKER
  - SHULKER_BULLET
  - SILVERFISH
  - SKELETON
  - SLIME
  - SMALL_FIREBALL
  - SNOWBALL
  - SPECTRAL_ARROW
  - SPIDER
  - SPLASH_POTION
  - STRAY
  - THROWN_EXP_BOTTLE
  - TRIDENT
  - UNKNOWN
  - VEX
  - VINDICATOR
  - WARDEN
  - WITCH
  - WITHER
  - WITHER_SKELETON
  - WITHER_SKULL
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN