notify-update:
  # Notifies Plugin Update
  enable: true
economy:
  # Economy Settings
  cost: 1250.0
  refund: 750.0
settings:
  # Claiming Settings
  claim:
    # Spigot particle list: "https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html"
    particle:
      # type: TOTEM
      type: TOTEM
    sound:
      # Spigot sound list: "https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html"
      # type: BLOCK_AMETHYST_BLOCK_BREAK
      # volume: 0.7F
      # pitch 1.0F
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.7F
      pitch: 1.0F
  un-claim:
    particle:
      # type: SPELL_INSTANT
      type: SPELL_INSTANT
    sound:
      # type: BLOCK_AMETHYST_BLOCK_BREAK
      # volume: 0.7F
      # pitch 1.0F
      type: BLOCK_AMETHYST_BLOCK_BREAK
      volume: 0.7F
      pitch: 1.0F
hostiles:
  - AREA_EFFECT_CLOUD
  - ARROW
  - BAT
  - BLAZE
  - CAVE_SPIDER
  - CREEPER
  - DRAGON_FIREBALL
  - DROPPED_ITEM
  - DROWNED
  - EGG
  - ELDER_GUARDIAN
  - ENDER_CRYSTAL
  - ENDER_DRAGON
  - ENDER_PEARL
  - ENDER_SIGNAL
  - ENDERMAN
  - ENDERMITE
  - EVOKER
  - EVOKER_FANGS
  - EXPERIENCE_ORB
  - FALLING_BLOCK
  - FIREBALL
  - FIREWORK
  - GHAST
  - GIANT
  - GUARDIAN
  - HOGLIN
  - HUSK
  - ILLUSIONER
  - LIGHTING
  - LLAMA_SPIT
  - MAGMA_CUBE
  - MARKER
  - PHANTOM
  - PIGLIN
  - PIGLIN_BRUTE
  - PILLAGER
  - PLAYER
  - PRIMED_TNT
  - RAVAGER
  - SHULKER
  - SHULKER_BULLET
  - SILVERFISH
  - SKELETON
  - SLIME
  - SMALL_FIREBALL
  - SNOWBALL
  - SPECTRAL_ARROW
  - SPIDER
  - SPLASH_POTION
  - STRAY
  - THROWN_EXP_BOTTLE
  - TRIDENT
  - UNKNOWN
  - VEX
  - VINDICATOR
  - WARDEN
  - WITCH
  - WITHER
  - WITHER_SKELETON
  - WITHER_SKULL
  - ZOGLIN
  - ZOMBIE
  - ZOMBIE_VILLAGER
  - ZOMBIFIED_PIGLIN